flowblade-trunk/Flowblade/app.py
flowblade-trunk/Flowblade/editorstate.py
flowblade-trunk/Flowblade/utils.py
flowblade-trunk/installdata/flowblade.1

see issue #161 for initial discussion

Add XDG support with -xdg flag

---

flowblade-trunk/Flowblade/locale/add_language

The script failed on case-sensitive systems.

Case mismatch in script and filename

---

flowblade-trunk/Flowblade/dialogs.py
flowblade-trunk/Flowblade/keyevents.py

Here are a couple of extra changes that probably should have been included in the previous pull request (to add 'end' key support). I'm still learning my way around the codebase!

End key: part 2

---

flowblade-trunk/Flowblade/res/help/developers

Change ratherlargerobot to Nathan Rosenquist
Thanks!

Update developer attribution file

---

flowblade-trunk/Flowblade/render.py

Render Folder from Preferences is not copied to Render panel #337

---

README.md

Very small fix to the README.md

Fixed Google+ group link Markdown

---

README.md

Correct vers. for upcoming release.

Fix version mistake in readme

---

flowblade-trunk/Flowblade/dialogs.py
flowblade-trunk/Flowblade/res/help/contributors
flowblade-trunk/Flowblade/res/help/developers
flowblade-trunk/Flowblade/res/help/translations

Little enhancement in Developers tab
**Suggestion for future:**
Link each name to their profile (either on github or anywhere they would prefer)

About menu enhancement - Developers and Translations tab

---

flowblade-trunk/docs/FAQ.md
flowblade-trunk/docs/RELEASE_NOTES.md

Formatted headings in Markdown files for proper display and navigation of TOC on github.com.

Formatted FAQ.md and RELEASE_NOTES.md for proper display and navigation.

---

flowblade-trunk/Flowblade/appconsts.py
flowblade-trunk/Flowblade/dialogs.py
flowblade-trunk/Flowblade/projectaction.py
flowblade-trunk/Flowblade/sequence.py

dialog now shows current V/A track counts (instead of 5/4)
Also made default V/A counts in to appconsts

Change Sequence Tracks Count

---

flowblade-trunk/setup.py

https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
(needed for flatpak)

setup.py: change icon path

---

flowblade-trunk/installdata/flowblade.xml

needs to be same as in `flowblade.desktop`

fix mimetype

---

flowblade-trunk/installdata/io.github.jliljebl.Flowblade.appdata.xml
flowblade-trunk/installdata/io.github.jliljebl.Flowblade.desktop

I forgot to rename some things in the last PR.

appdata: fix names, add more data

---

flowblade-trunk/Flowblade/res/profiles/wqhd_1440p_2398
flowblade-trunk/Flowblade/res/profiles/wqhd_1440p_24
flowblade-trunk/Flowblade/res/profiles/wqhd_1440p_25
flowblade-trunk/Flowblade/res/profiles/wqhd_1440p_2997
flowblade-trunk/Flowblade/res/profiles/wqhd_1440p_30
flowblade-trunk/Flowblade/res/profiles/wqhd_1440p_50
flowblade-trunk/Flowblade/res/profiles/wqhd_1440p_5994
flowblade-trunk/Flowblade/res/profiles/wqhd_1440p_60

This patch adds WQHD 1440p (2560×1440) frame presets.

Add WQHD 1440p presets

---

flowblade-trunk/Flowblade/undo.py

import time for access to time.sleep() on lines 158 and 164

---

flowblade-trunk/Flowblade/projectmediaimport.py

```
./flowblade-trunk/Flowblade/projectmediaimport.py:205:41: F821 undefined name 'appconsts'
if editorpersistance.prefs.theme != appconsts.LIGHT_THEME:
^
./flowblade-trunk/Flowblade/projectmediaimport.py:207:45: F821 undefined name 'appconsts'
if editorpersistance.prefs.theme == appconsts.FLOWBLADE_THEME:
^
```

Undefined name: import appconsts for lines 206 and 208

---

flowblade-trunk/Flowblade/tools/natronanimationswindow.py

```
./flowblade-trunk/Flowblade/tools/natronanimationswindow.py:176:5: F821 undefined name 'processutils'
processutils.prepare_mlt_repo(repo)
^
```

import processutils for access to prepare_mlt_repo()

---

flowblade-trunk/Flowblade/workflow.py

maybe this will reduce your time, the translation will also have to be updated

Welcome to Flowblade 2.0 updated to ... 2.2

---

flowblade-trunk/Flowblade/rendergui.py

Undefined name detected via #607

Undefined name: IconSize.DND -> Gtk.IconSize.DND

---

flowblade-trunk/Flowblade/res/filters/filters.xml

Simple fixes so some of the filters behave better straight out of the box

Filterfixups

---

flowblade-trunk/Flowblade/tools/exportardour.py

This is a standalone command-line script to convert a Flowblade MLT XML file
into a new Ardour project for post-production sound editing.
See https://github.com/jliljebl/flowblade/issues/666 for details
Usage: ./exportardour.py exported-flowblade-mlt.xml /path/to/new-ardour-dir
The sample rate (in hertz, e.g. 48000) can be added as an optional third
positional command-line argument.

Add tools/exportardour.py script

---

flowblade-trunk/Flowblade/tools/exportardour.py

I tried adding a compound clip to the timeline and exporting that timeline to Ardour, which uncovered an audio sync bug. This pull request contains an update that attempts to fix that. It won't extract audio from compound clips, but at least it should fix the sync issue that was created on subsequent clips in the playlist.
--
Prior to this commit, exportardour.py did not take into account
compound clips. This means that if a compound clip appeared on
the timeline, it got completely ignored, but it also skewed the
timeline for all subsequent clips in the same playlist. Basically
like perfoming a delete edit on the compound clip.
Actually extracting audio from compound clips seems non-trivial.
Even some of the well-known proprietary programs had limitations
on OMF/AAF export of audio in …

Add audio sync fix when timeline has compound clips

---

flowblade-trunk/Flowblade/atomicfile.py

This commit adds better error handling and testability to the
atomicfile module.
Summary of changes:
- AtomicFileWriter mode argument ("w" or "wb") is now required,
since Python 3 really cares about the distinction
- AtomicFileWriter now has an optional debug mode, disabled by
default, that prints out information about what it's doing when
it creates/deletes temp files, renames files, etc.
- Improved error handling if os.rename() fails, especially
with regard to cleaning up temp files
- New command-line mode to make testing the module easier
If you run `python3 atomicfile.py /path/to/some/file`, it will try
to write a test file to the given path using AtomicFile in debug
mode, which will print out information about creating/deleting/renaming
temp files, etc.

Add various atomicfile improvements

---

flowblade-trunk/Flowblade/locale/uk/LC_MESSAGES/flowblade.po

If I have time this year I will transfer 100%. So far, the translation into Ukrainian is 56% ready.

Addition to the translation into Ukrainian

---

flowblade-trunk/Flowblade/editorpersistance.py
flowblade-trunk/Flowblade/editorwindow.py
flowblade-trunk/Flowblade/glassbuttons.py
flowblade-trunk/Flowblade/monitorevent.py
flowblade-trunk/Flowblade/movemodes.py
flowblade-trunk/Flowblade/preferenceswindow.py

In the Preferences window, playback tab, a check button can show or hide these two buttons.
I cannot know how to center vertically the png images inside the buttons.

Add two buttons go at start or end of the timeline

---

flowblade-trunk/Flowblade/editorwindow.py

"Home"-Go To Start
"End"-Go To End

Fixed "start key" to "home key"

---

flowblade-trunk/Flowblade/res/render/renderencoding.xml

Some minor fixes and a workaround for #842

AAC MP3 workaround #842

---

flowblade-trunk/Flowblade/appconsts.py
flowblade-trunk/Flowblade/guicomponents.py
flowblade-trunk/Flowblade/sequence.py
flowblade-trunk/Flowblade/tlinewidgets.py
flowblade-trunk/Flowblade/trackaction.py

The tracks have a height of 50 and 25 pixels. This merge request add a track of 75 pixels so the the thumbnails of the clips are as large as the thumbnails of the media panel.
Two ways to have this height :
Right click on the header of the track and select the radio button "High height"
Double left click on the header of the track ; the height changes in this order : Normal -> Large -> High -> Normal

Track of 75 pixels

---

flowblade-trunk/setup.py

Otherwise the help is missing from the installation.

Install subdirectories of help

---

flowblade-trunk/installdata/io.github.jliljebl.Flowblade.xml

mime: add icon, fixes #905

---

flowblade-trunk/Flowblade/tools/titler.py

Titler : remove spaces and new line characters at start of the name of a layer

---

flowblade-trunk/Flowblade/kftoolmode.py

See the [105]((https://github.com/jliljebl/flowblade-forum/issues/105)) item in the forum

Move an horizontal keyframe curve in one click

---

flowblade-trunk/Flowblade/locale/ru/LC_MESSAGES/flowblade.po

The translation is not completed completely, but I hope to complete it within a month (June-July). I will also try to translate the manual by the end of July.

Russian translation update

---

flowblade-trunk/Flowblade/res/help/en/advanced.html

Apologies, this corrects a typo introduced in a previous commit.

Fix previously introduced typo

---

flowblade-trunk/Flowblade/propertyparse.py
flowblade-trunk/Flowblade/res/help/advanced.html
flowblade-trunk/Flowblade/tools/scripttool.py

Fix remaining typos
