flowblade-trunk/Flowblade/tools/titler.py

Currently the titler dialog does not saven the last location. Clicking on "Save" always goes back to the home directory. When saving more than one title you have to navigate back to the last directory.
This pull requests saves the last location and hence the file chooser opens at the last location.

Titler dialog saves last location

---

flowblade-trunk/Flowblade/keyevents.py
flowblade-trunk/Flowblade/mltplayer.py

The 'home' key seeks to the first frame in timeline navigation, but the
'end' key was previously unsupported. This commit gives the 'end' key
feature parity so that a user can press both the 'home' and 'end' keys
to navigate to the beginning and end of the timeline.
By the way, thanks for creating Flowblade, it's excellent!

Add 'end' key support, for parity with 'home' key

---

flowblade-trunk/Flowblade/projectaction.py

This one-line update simply updates the bin file count after files are deleted.
Previously, the bin file count GUI element would not get updated after a delete, so the numbers there wouldn't change until something else triggered a visual update.

Update bin file count after deleting files

---

flowblade-trunk/Flowblade/utils.py

This update fixes time code calculations for NTSC frame rates like 23.976 and 29.97.
Before this update, a 60 second (24 * 60 frame) clip in 23.976 frame rate would display a length of "00:01:00:01" in the media clip view list. And a timeline made up of 60 instances of this same clip would
end on "01:00:03:13" as the last frame.
After this update, the same clip shows a length of "00:01:00:00" in the media clip view list, and a timeline made up of 60 instances of this same clip ends on "00:59:59:23".
---
By the way, I double checked that this new behavior is in line with other popular commercial editing programs. I really wish NTSC would have just switched over to a pure 24 FPS during the HD transition...

Round FPS to whole numbers for NTSC time code

---

flowblade-trunk/Flowblade/editorpersistance.py
flowblade-trunk/Flowblade/preferenceswindow.py
flowblade-trunk/Flowblade/projectdata.py

When you add media clips to your project, the default setting is for the
clips to receive the name of the file as the clip name. For example, if
you add 'Scenes/011/11A-3.MOV' into your project, the name of the clip
will be '11A-3.MOV'.
This commit adds an optional user preference to omit the file extension
on the clip name when adding files into your project. For example, the
previously mentioned clip would now receive the name '11A-3' during
import instead.
This preference is controlled by a checkbox under:
Edit -> Preferences -> Editing ->
[ ] Hide file extensions when importing Clips
For backwards compatibility, this option is disabled by default, so
existing users should not notice any change in behavior.
---
This feature is useful for me, but comments, suggestions, and constructive …

Add option to hide file extensions during import

---

flowblade-trunk/docs/DEPENDENCIES.md

**python2-rsvg** has been deprecated by Archlinux. **librsvg** (pulled in as a depends of **gtk3** anyway) seems to be sufficient.

Update Archlinux dependencies

---

flowblade-trunk/Flowblade/editorpersistance.py
flowblade-trunk/Flowblade/preferenceswindow.py
flowblade-trunk/Flowblade/renderconsumer.py

Changes include:
1. New Preferences tab 'Performance'
2. Performance options 'Render Threads' (limited to the number of cores as reported by the system - default 1) and 'Allow Frame Dropping' (default False)
3. Options under 2) will be passed as value to the mlt consumer real_time parameter. Allow Frame Dropping translates to 1 (True) or -1 (False) and is multiplied by the number of render threads

Performance patch (real_time parameter)

---

flowblade-trunk/Flowblade/editorpersistance.py
flowblade-trunk/Flowblade/guicomponents.py
flowblade-trunk/Flowblade/mltprofiles.py
flowblade-trunk/Flowblade/preferenceswindow.py

Preference setting (In View tab) to show full file names in the media list.
When unticked (Default) it will show as it is now, when ticked all files will show their full file name.
No need to restart the application. Setting will be activated once a file is added or removed in the media list.

Filenames in Media-List - issue 267

---

flowblade-trunk/Flowblade/persistance.py

Removed print of project.name in the debugging message. This will allow the project to load if it has non-latin characters in the name.
No real reason found why it is a problem, but any manipulation on project.name (If it contains non-latin characters, like characters with tilde, accents, cedilles etc.) causes the project load to stop.

Unpickling...¿? #341

---

flowblade-trunk/installdata/flowblade.xml

Slight change in xml file should associate Flowblade logo to flb files.
To test manually, update flowblade.xml in /usr/share/mime/packages
and then run
sudo update-mime-database /usr/share/mime/
then open file browser and flb files should have the Flowblade logo associated to them.
To revert, revert the changes to flowblade.xml and rerun
sudo update-mime-database /usr/share/mime/
close and re-open the file browser and the flb files have the current logo.

Thumbnail icon for flb project files? #346

---

flowblade-trunk/Flowblade/res/render/renderencoding.xml

Encoding parameters taken from https://amiaopensource.github.io/ffmprovisr/#create_FFV1_mkv

Add Lossless FFv1 profile

---

flowblade-trunk/Flowblade/editorpersistance.py
flowblade-trunk/Flowblade/keyevents.py
flowblade-trunk/Flowblade/preferenceswindow.py

Instead of the hardcoded 10x speed for Ffwd / Rev add user preferences to set the speed (1..10) on each of these keys: Shift, Ctrl, CapsLock (NB: Use of Alt or Meta would need remapping as standard assignment of Alt+Ctrl + Left (Or Right arrow) is to move to another workspace, so it was easiest to use CapsLock as a third modifier)
The user can set each of the modifiers to 1..10 and the resulting Ffwd / Rev speeds is the multiplication of the values (limited by software / hardware restrictions, though).
This allows fine control of Ffwd / Rev speeds by combining Right / Left arrow and Shift or Shift + Ctrl or just Ctrl or any of the 3 keys set up.
It speeds up scanning through the clips (Or the project timeline) tremendously.

Allow user preferences for Fast Forward / Reverse speeds

---

flowblade-trunk/Flowblade/editorwindow.py
flowblade-trunk/Flowblade/guicomponents.py
flowblade-trunk/Flowblade/middlebar.py
flowblade-trunk/Flowblade/updater.py
flowblade-trunk/Flowblade/utils.py

- Added a GtkEntry class named BigTCEntry that offers functionality for manually entering a time code to jump to.
- Replaced editor_window.big_TC and gui.big_tc with GtkStack containing BigTCDisplay.widget and BigTCEntry.widget
- implemented a mouse click event handler on BigTCDisplay that makes BigTCEntry visible, when clicked on BigTCDisplay
- implemtented a enter pressed and focus lost event handler that will make PLAYER() jump to entered time code and make BigTCDisplay visible again
General Description:
When time display in middlebar is clicked an entry field will be displayed instead, that offers you the possibility to manually enter a time code.
You may leave the entry by pressing TAB or ENTER. The cursor will jump to frame of timecode if valid.
Things that might still need …

Support for manual entered time codes

---

flowblade-trunk/Flowblade/atomicfile.py
flowblade-trunk/Flowblade/persistance.py

This pull request introduces the atomicfile module, containing the AtomicFileWriter class.
As a proof of concept, it also migrates some file writing code in the persistance.py module to use the AtomicFileWriter class instead of writing the files directly.
What do you think?

atomicfile module and proof of concept

---

flowblade-trunk/Flowblade/guicomponents.py

Replace hardcoded constant 8 and 9 with variable.
Allow no audio tracks. Still must have at least one video track, allow all tracks to be video.
This doesn't actually change MAX_TRACKS (In appconsts.py), but allows for it to be increased.
(I'm not sure if there is any hidden limitation in underlying libraries or project save/load that means that changing MAX_TRACKS from 9 would not work?)

Track count dialog correctly adapt to changed MAX_TRACKS

---

flowblade-trunk/installdata/flowblade.appdata.xml
flowblade-trunk/setup.py

This file is used in software managers like GNOME Software or KDE Discover to display information. It is also used on Flathub: https://flathub.org/apps/details/io.github.jliljebl.Flowblade

add appdata

---

flowblade-trunk/Flowblade/undo.py

Make line 150 like line 50.
```
./flowblade-trunk/Flowblade/undo.py:154:15: F821 undefined name 'undo'
while undo.index > 0:
^
./flowblade-trunk/Flowblade/undo.py:155:28: F821 undefined name 'undo'
print "undo:", undo.index
^
./flowblade-trunk/Flowblade/undo.py:160:15: F821 undefined name 'undo'
while undo.index < len(undo.undo_stack):
^
./flowblade-trunk/Flowblade/undo.py:160:32: F821 undefined name 'undo'
while undo.index < len(undo.undo_stack):
^
./flowblade-trunk/Flowblade/undo.py:161:28: F821 undefined name 'undo'
print "redo:", undo.index
^
```

Undefined name: global undo_stack, index in undo.py

---

flowblade-trunk/Flowblade/jackaudio.py

```
./flowblade-trunk/Flowblade/jackaudio.py:61:9: F821 undefined name 'Gdk'
Gdk.threads_enter()
^
./flowblade-trunk/Flowblade/jackaudio.py:63:9: F821 undefined name 'Gdk'
Gdk.threads_leave()
^
```

from gi.repository import Gdk for lines 63 and 65

---

flowblade-trunk/Flowblade/utils.py

__expression__ is never defined and __identifier__ is never used.
```
./flowblade-trunk/Flowblade/utils.py:158:12: F821 undefined name 'expression'
except expression as identifier:
^
```

Undefined name: 'expression' is never defined

---

flowblade-trunk/Flowblade/jackaudio.py

When line 174 was commented out, it created _undefined names_ on lines 175, 176, and 178.  An alternative approach would be to comment out all four lines.
```
./flowblade-trunk/Flowblade/jackaudio.py:148:59: F821 undefined name '_convert_to_original_media_project'
self.dont_use_button.connect("clicked", lambda w: _convert_to_original_media_project())
^
./flowblade-trunk/Flowblade/jackaudio.py:175:9: F821 undefined name 'alignment'
alignment.set_padding(12, 12, 12, 12)
^
./flowblade-trunk/Flowblade/jackaudio.py:176:9: F821 undefined name 'alignment'
alignment.add(vbox)
^
./flowblade-trunk/Flowblade/jackaudio.py:178:37: F821 undefined name 'alignment'
self.dialog.vbox.pack_start(alignment, …
```

Uncomment line 174 for lines 175, 176, 178

---

flowblade-trunk/Flowblade/diskcachemanagement.py
flowblade-trunk/Flowblade/proxyediting.py

This fixes the traceback error in issue #660 and proxy files are rendering without any errors.

import userfolders to fix proxy rendering and misc typos

---

flowblade-trunk/Flowblade/diskcachemanagement.py
flowblade-trunk/Flowblade/tlineaction.py
flowblade-trunk/Flowblade/tools/phantomcompositor.py
flowblade-trunk/Flowblade/userfolders.py

[flake8](http://flake8.pycqa.org) testing of https://github.com/jliljebl/flowblade on Python 2.7.15
$ __flake8 . --builtins=_ --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./flowblade-trunk/Flowblade/userfolders.py:138:38: F821 undefined name 'mltprofiles'
if not os.path.exists(user_dir + mltprofiles.USER_PROFILES_DIR):
^
./flowblade-trunk/Flowblade/userfolders.py:139:29: F821 undefined name 'mltprofiles'
os.mkdir(user_dir + mltprofiles.USER_PROFILES_DIR)
^
./flowblade-trunk/Flowblade/userfolders.py:140:38: F821 undefined name 'AUTOSAVE_DIR'
if not os.path.exists(user_dir + AUTOSAVE_DIR):
^
./flowblade-trunk/Flowblade/userfolders.py:141:29: F821 undefined name 'AUTOSAVE_DIR'
os.mkdir(user_dir + AUTOSAVE_DIR)
^
./flowblade-trunk/Flowblade/userfolders.py:142:38: F821 …
```

Undefined names: Add missing imports

---

flowblade-trunk/flowblade

This ensures that even if flowblade is installed in /bin or /usr/local/bin that it finds the modules correctly and is able to launch. Otherwise, it cannot find the processutils module and does not launch.
I apologize for submitting this during the project summer break. Please do not start on addressing this until August.
Thank you for any reply, and please let me know if there is anything I have missed.

Change launch script for variant install locations

---

flowblade-trunk/Flowblade/res/render/renderencoding.xml

Add a higher quality (but still pretty fast) proxy format, considering the MPEG4 Preset ultrafast seems to deliver very poor quality

renderencoding: add h.264 proxy format

---

flowblade-trunk/Flowblade/keyframeeditor.py

As I mentioned I think the keyframeeditor also sticks out a bit, here a single change to make it fit better into the theme.
It would be even better if these colors would be abstracted away into the CSS though.

Keyframededitor: match Flowblade theme colors

---

flowblade-trunk/Flowblade/res/filters/filters.xml

While it may not be suitable for all lenscorrection, in many ways it's
superior to the other lenscorrection filters.
As it offers autoscaling and proper pixel interpolation.
I've had success using it to remove distortion from a non-fisheye lens
as well, and I would encourage anybody to try defish0r before trying
the other lenscorrection plugins.

filters: add frei0r defish0r

---

flowblade-trunk/Flowblade/tools/exportardour.py

The Ardour session file format has two fields for the name of the
program that created and modified the Ardour session.
Previously, exportardour.py was using "exportardour.py" as the
program name. However, now that it is being integrated into
Flowblade, I have changed this value to "Flowblade".
What I really wanted to do was to reference entries in
appconstants.py for the Flowblade program name and version, and
concatenate them together. However, I didn't find any suitable
fields in there, so I hard-coded it for now.

Add 'Flowblade' program name to Ardour project

---

flowblade-trunk/docs/creating_user_folder_bindings.md

These instructions worked great on my computer. The only thing that was missing was the Python 3 numpy dependency.

Add numpy dependency to python3 doc

---

flowblade-trunk/Flowblade/res/filters/filters.xml

This commit fixes a regression where .cube files (lowercase)
could not be loaded in the Lut3D filter.
The ability for the Lut3D filter to load .cube files stopped
working. I traced this back to a formatting mismatch between
the following two files:
flowblade-trunk/Flowblade/propertyeditorbuilder.py
flowblade-trunk/Flowblade/res/filters/filters.xml
When propertyeditorbuilder.py loads lists of file types to use
when filtering results in the GTK file picker, it is expecting
to find them as a string with a dot preceeding each file
extension, e.g.: ".cube.CUBE"
The filters.xml file only currently has one file_types setting,
and it is for the Lut3D filter. Before this commit, it had the
file types for 3D LUT file extensions specified with a comma
separating them, e.g. ".cube,.CUBE"
This …

Fix Lut3D file type regression

---

flowblade-trunk/Flowblade/res/render/renderencoding.xml

Lossless HuffYUV and Apple ProRes 4:2:2 look like the two highest
quality formats with Flowblade render presets. This commit changes
the audio format for these two formats from 16-bit audio to 24-bit
audio.
Additionally, the Apple ProRes preset gains a YUV format setting
and an Apple vendor ID, which make the rendered clips playable on
a Mac using QuickTime. Without these options, QuickTime can't
decipher the files (although VLC can, of course).

Change Lossless HuffYUV and Apple ProRes 4:2:2 to use 24-bit audio

---

flowblade-trunk/Flowblade/renderconsumer.py
flowblade-trunk/Flowblade/tools/gmic.py

I tried to render a movie using custom render args from Flowblade
on the master branch. However, it bumped into a decode() call on
a string.
This would have worked on Python 2. But decode() is no longer a
valid method on strings in Python 3.
There were two main instances of this:
1) A key and value in renderconsumer.py, which were previously
being checked to ensure they were in ASCII format
2) A decode() call on a string in gmic.py
I removed all of these decode() calls in this commit, but I'm not
completely sure that everything is correct.
For one thing, it is now possible to have non-ASCII characters
get through in renderconsumer.py. I'm not sure if that's an issue
or not. This commit just removes those decode() calls, but if they
still need to be ASCII, then something else should be put …

Remove left over Python 2 string decode() calls

---

flowblade-trunk/Flowblade/atomicfile.py
flowblade-trunk/Flowblade/persistance.py

The Flowblade project file uses the Python pickle format.
In Python 3, strings and bytes must be kept separate.
The pickle format is binary.
When writing a pickle file, you must open the filehandle with the
"wb" mode (write binary).
AtomicFileWriter was previously only using "w" mode, even when "wb"
was specified.
Now, AtomicFileWriter respects the file write mode setting when
opening files. As a result, saving project files can be done
atomically again, and once again uses atomicfile as a wrapper
around the file writes to avoid the possibility of the project
file being corrupted if the save doesn't complete.

Save project using atomicfile (in Python 3)

---

flowblade-trunk/Flowblade/tools/exportardour.py

tools/exportardour.py started out as a command-line script with
no dependencies on Flowblade. But now it's integrated into Flowblade,
and can take advantage of more of Flowblade's features.
Since the command-line interface was basically a proof of concept, the
command-line interface is dropped here, in favor of making Ardour
session exports perform better from within the Flowblade GUI.
- All CLI/GUI conditional code is gone now.
- atomicfile is used when writing the Ardour session file
- The Flowblade version number is included in the created/modified
fields of the exported Ardour session file
- MLT XML playlist and Flowblade track name mapping now works when
an alternate number of audio/video tracks is used in the Flowblade
sequence being exported
- The Flowblade copyright header was …

Improve Ardour export integration

---

flowblade-trunk/Flowblade/res/render/renderencoding.xml

Flowblade has the ability to create proxy clips. This commit adds the ability to use the "Apple ProRes 422 Proxy" codec for these proxy clips.

Add Apple ProRes 422 Proxy as a proxy encoding option

---

flowblade-trunk/Flowblade/guicomponents.py

Previously, if you went to the Change Project Profile dialog and
selected a project profile with fractional frame rates, it would
show you as many decimal points as Python could calculate
(e.g. 23.976023976023978).
This commit adds some code that selectively rounds frame rates in
the Change Project Profile dialog to two decimal points, but leaves
non-fractional frame rates as whole integers without any decimal
points. Basically, the integer frame rates look the same as always,
but the NTSC frame rates look more like what you would expect.

Round fractional fps in Change Project Profile dialog

---

flowblade-trunk/Flowblade/res/profiles/dci_2k_2398
flowblade-trunk/Flowblade/res/profiles/dci_2k_24
flowblade-trunk/Flowblade/res/profiles/dci_2k_25
flowblade-trunk/Flowblade/res/profiles/dci_2k_2997
flowblade-trunk/Flowblade/res/profiles/dci_2k_50
flowblade-trunk/Flowblade/res/profiles/dci_2k_5994
flowblade-trunk/Flowblade/res/profiles/dci_4k_2398
flowblade-trunk/Flowblade/res/profiles/dci_4k_24
flowblade-trunk/Flowblade/res/profiles/dci_4k_25
flowblade-trunk/Flowblade/res/profiles/dci_4k_2997
flowblade-trunk/Flowblade/res/profiles/dci_4k_50
flowblade-trunk/Flowblade/res/profiles/dci_4k_5994
flowblade-trunk/Flowblade/res/profiles/uhd_2160p_2398
flowblade-trunk/Flowblade/res/profiles/uhd_2160p_24
flowblade-trunk/Flowblade/res/profiles/uhd_2160p_25
flowblade-trunk/Flowblade/res/profiles/uhd_2160p_50
flowblade-trunk/Flowblade/res/profiles/uhd_2160p_5994
flowblade-trunk/Flowblade/res/profiles/uhd_2160p_60
flowblade-trunk/Flowblade/res/profiles/uhd_4320p_2398
flowblade-trunk/Flowblade/res/profiles/uhd_4320p_24
flowblade-trunk/Flowblade/res/profiles/uhd_4320p_25
flowblade-trunk/Flowblade/res/profiles/uhd_4320p_2997
flowblade-trunk/Flowblade/res/profiles/uhd_4320p_30
flowblade-trunk/Flowblade/res/profiles/uhd_4320p_50
flowblade-trunk/Flowblade/res/profiles/uhd_4320p_5994
flowblade-trunk/Flowblade/res/profiles/uhd_4320p_60

This commit adds a number of project profile settings, and changes
some existing profile settings.
DCI 2K and DCI 4K profiles are added, in a variety of frame rates.
The Digital Cinema Initiative defines a maximum 2K and 4K resolution
of 2048x1080 and 4096x2160, respectively. These profiles don't
completely adhere to the DCI spec (due to colorspace and frame rate
differences). However, the Fujifilm X-T3 and Atmos Ninja recorders
support these settings, and Fujifilm is calling their 4096x2160
resolution setting DCI. Technically the 24 fps DCI settings are the
closest to actually being compliant, but real DCI requires the P3
color space, 12 bits per channel, etc. Never the less, now you can
take footage from a Fujifilm mirrorless camera in these resolutions,
drop it into a new Flowblade …

Add/update selected 2K/4K/8K profiles

---

flowblade-trunk/Flowblade/res/render/renderencoding.xml

Previously, we only had a single ProRes render option, which was not
configured optimally.
This commit exposes more of the underlying ffmpeg ProRes options.
The previous "Apple ProRes 4:2:2" entry was removed. Two new entries
were added: "Apple ProRes 422", and "Apple ProRes 4444". I tried to
merge them into a single "Apple ProRes" entry in renderencoding.xml,
but this didn't work because some of the options that needed to be
changed didn't play well with some assumptions in Flowblade about
the vcodec setting (each entry uses a different ffmpeg codec). I
tried to set vcodec dynamically using replvalues, but couldn't quite
get that to work.
ProRes is a family of related codecs tuned for different quality
settings, so instead of tuning qscale or VBR settings, you instead
switch to a …

Refactor ProRes render options

---

flowblade-trunk/Flowblade/audiowaveform.py
flowblade-trunk/Flowblade/audiowaveformrenderer.py
flowblade-trunk/Flowblade/editorpersistance.py
flowblade-trunk/Flowblade/exporting.py
flowblade-trunk/Flowblade/gui.py
flowblade-trunk/Flowblade/profilesmanager.py
flowblade-trunk/Flowblade/projectmediaimport.py
flowblade-trunk/Flowblade/proxyediting.py
flowblade-trunk/Flowblade/render.py
flowblade-trunk/Flowblade/tools/batchrendering.py
flowblade-trunk/Flowblade/tools/exportardour.py
flowblade-trunk/Flowblade/tools/gmic.py
flowblade-trunk/Flowblade/tools/titler.py

I went through the codebase and found all of the places where files
were written using the open() call, and checked each of them to
see if they could be converted to use atomicfile instead.
Some of the calls to open() were doing things that didn't seem
appropriate for atomicfile to handle. Things like writing log files
that might be watched in realtime. Anything involving Popen, FLOG,
stdout, stderr, or dup2().
Additionally, there are other instances where files are written
directly by other programs like ffmpeg. These were not addressed
either.
After that, there were a dozen or so calls that were mostly writing
project files, prefs files, EDLs, and things like that, where the
pattern was to write a file all in one shot. All of these instances
were converted from using open()/close() to …

Use atomicfile in most places files are written

---

flowblade-trunk/Flowblade/res/help/en/advanced.html

"Project-> Sequence" The word Project has been deleted because the Sequence has been taken out of the menu.
Line "Select Edit -> Resync All to resync from application menu all Sync Child Clips." has been removed because this feature is missing from the interface.

text revision

---

flowblade-trunk/Flowblade/guiutils.py

Added code so Flowblade no longer crashes if @2 images are missing.
Instead it will load the original image.

Ignore missing @2 images

---

flowblade-trunk/docs/KEYBOARD_SHORTCUTS.md

Noticed that the paste filters shortcut was not listed in the docs, but was listed in issues (https://github.com/jliljebl/flowblade-forum/issues/23).
Wanted to fix that for other people looking for the same thing!

Add Paste Filter shortcut

---

flowblade-trunk/flowblade

In the Linux world, some distribution started to merge:
- /bin into /usr/bin
- /sbin into /usr/sbin
- /lib into /usr/lib
Some distro go with more extreme approach, merge `/bin`, `/sbin`,
`/usr/sbin` into `/usr/bin`.
See: https://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/
Let's use `os.path.realpath` to see if we're starting up from distro
installation or not. If distro follow correctly usr-merge specs, the
target of symlink should always in `/usr/bin`.

startup: support usr-merge

---

flowblade-trunk/setup.py

See: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location

Don't use legacy directory for Appstream metadata

---

flowblade-trunk/Flowblade/editorwindow.py

Hello!
I tried to start flowblade from the Git repo, but it failed with references to an invalid reference called "ui", which I believe was supposed to refer to the Gtk.UIManager instance.
This pull request changes all references to "ui" to "self.ui" inside of the EditorWindow class. After making these changes, the program started up for me successfully.

Attempt to fix broken 'ui' object references in editorwindow.py

---

flowblade-trunk/Flowblade/medialinker.py

If you have to change the directory of your project medias for some reason, the number of files to relink can be significant. This is not practical because Flowblade relinks file by file. I modify the behaviour.
In this request, when you relink a file, Flowblade search in the relink directory of the relink file if other files have the same names (basename in python) of the project files which cannot be found. Media Relink adds them in the list of files to relink.

Relink a directory from a file

---

.github/workflows/build.yml

This creates a GitHub Action to build nightly and on-demand. The build is not very usable outside Ubuntu 18.04 due to non-bundled dependencies that are not easily available on other distros. For example, Python 3.6 for MLT Python binding and libsndio 6.0 for FFmpeg are required but not available in Ubuntu 20.04. Making the build more usable could be done in `build-flowblade.sh` in the mlt-scripts repo by bundling libs from the build host or extending this workflow to create an AppImage. Otherwise, this is a hand-off from our nightly build server, which is retiring soon, and gives you a starting point. You will not see anything in GitHub Actions until you merge into your master branch due to how it works, but after seeding master you can develop on it further in a branch and manually …

add GitHub Actions build workflow

---

flowblade-trunk/Flowblade/editorlayout.py

This can only apply to the Russian language, but Kdenlive uses these names for the position of the tabs. You can ignore or postpone this merge if you think it might adversely affect language translations, or the code is frozen. The names used today are applicable for moving bins, but not correct for the layout of tabs.

Split naming position of tabs and bins

---

flowblade-trunk/Flowblade/translations.py

translations.py refers to a filter called Pitchshifter, although there is no such filter in filters.xml, but there is a filter called Pitchshifter - AM. If I understand correctly, it is he who means.

Refine the filter name

---

flowblade-trunk/Flowblade/res/filters/filters.xml

The "RGB Shift" filter parameter has a typo "Verical" corrected to "Vertical". Since "Shift" is a key on the keyboard, it is not translated into other languages, which means that translation into any other language of this parameter will not be available. I suggest the names of the "Glitch" filter parameters from Kdenlive.

Fixed typo and renaming of parameters: Glitch

---

flowblade-trunk/Flowblade/dialogs.py
flowblade-trunk/Flowblade/exporting.py
flowblade-trunk/Flowblade/guicomponents.py
flowblade-trunk/Flowblade/tools/exportardour.py

Previously, all Ardour exports defaulted to a 48 kHz sampling rate. This is
usually the right choice for a film or video project, but there are other
sample rates available, and some projects might want to choose a different
one.
This commit adds a sample rate combo select box to the Ardour export
dialog. It still defaults to 48 kHz as before. But now it also offers
three other choices.
The sample rates now available are:
44.1 kHz
48 kHz (default)
88.2 kHz
96 kHz
Some audio interfaces go up even higher than that, to 192 or 384. I've
never heard of a film or video project using them though, and question
the diminishing returns. It would be easy to add more sample rates
later if it really turns out to be useful to anyone.

Add selectable sample rate to Ardour export

---

flowblade-trunk/Flowblade/guicomponents.py
flowblade-trunk/Flowblade/updater.py

The documentation states that the TAB key switches between the
timeline and the selected media clip in the monitor. However, it
didn't seem to actually work.
I have restored this functionality, and the tab key now toggles
between the media clip and the timeline in the monitor as expected.

Fix tab hot key monitor switching

---

flowblade-trunk/docs/INSTALLING.md

Update Arch Linux package URL in INSTALLING.md

---

flowblade-trunk/docs/INSTALLING.md

The flowblade package is no longer in AUR, no need to use an AUR helper to install it

INSTALLING.md: use correct package manager for arch linux

---

flowblade-trunk/Flowblade/projectaction.py

Fix this error: NameError: name 'PEOJECT' is not defined. Did you mean: 'PROJECT'?

Fix typo PEOJECT -> PROJECT
